FROM continuumio/miniconda3:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update

RUN git clone https://github.com/globus-labs/mof-generation-at-scale.git

COPY environment-cuda11.yml /mof-generation-at-scale/envs/environment-cuda11.yml

RUN conda update -n base conda \
    && conda install -n base conda-libmamba-solver \
    && conda config --set solver libmamba \
    && cd mof-generation-at-scale/envs \
    && conda env create --file environment-cuda11.yml

SHELL ["conda", "run", "--no-capture-output", "-n", "mofa", "/bin/bash", "-c"]
RUN conda install -y redis mongodb

COPY run_mini_app.sh /mof-generation-at-scale/

LABEL org.opencontainers.image.source=https://github.com/diaspora-project/mofa-mini-app

ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "mofa", "/bin/bash", "/mof-generation-at-scale/run_mini_app.sh"]
