services:

  thinker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thinker
    env_file:
      - secrets.env
    environment:
       - LAUNCH_OPTION=thinker
       - QUEUE_TYPE=octopus
       - REDIS_HOST=redis-service
       - PROXYSTORE_ENDPOINT_NAME=ep8765
       - PROXYSTORE_ENDPOINT_PORT=8765
    deploy:
      resources:
        limits:
          memory: 24g
    depends_on:
      - redis-service

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    env_file:
      - secrets.env
    environment:
       - LAUNCH_OPTION=server
       - QUEUE_TYPE=octopus
       - REDIS_HOST=redis-service
       - PROXYSTORE_ENDPOINT_NAME=ep8766
       - PROXYSTORE_ENDPOINT_PORT=8766
    deploy:
      resources:
        limits:
          memory: 24g
    depends_on:
      - redis-service

  redis-service:
    image: redis:latest
    container_name: redis-service
    ports:
      - "6379:6379"
