services:
  docker:
    image: mofa-app
    platform: linux/amd64
    environment:
      - OCTOPUS_LAUNCH_OPTION=both
      - OCTOPUS_AWS_ACCESS_KEY_ID=${OCTOPUS_AWS_ACCESS_KEY_ID}
      - OCTOPUS_AWS_SECRET_ACCESS_KEY=${OCTOPUS_AWS_SECRET_ACCESS_KEY}
      - OCTOPUS_BOOTSTRAP_SERVERS=${OCTOPUS_BOOTSTRAP_SERVERS}
      - PROXYSTORE_GLOBUS_CLIENT_ID=${PROXYSTORE_GLOBUS_CLIENT_ID}
      - PROXYSTORE_GLOBUS_CLIENT_SECRET=${PROXYSTORE_GLOBUS_CLIENT_SECRET}
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
    deploy:
      resources:
        limits:
          memory: 24g
